services:
  mongo-db:
    image: mongo:7.0
    container_name: mongodb-user-store
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27025:27017

  postgres-db:
    image: postgres:16
    container_name: postgresdb-user-store
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my-db
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
